version: '3'
services:
 app:
    build: .
    ports:
      - "9200:9200"
    depends_on:
      - elasticsearch
    # volumes:
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9201"
