version: '3'
services:
 go-places-app:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - elasticsearch
    container_name: go-places-app
    networks:
      - go-places-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - go-places-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
 go-places-network:
    driver: bridge
